version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "florianrusch"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    reviewers:
      - "florianrusch"
    labels:
      - "dependencies"
