linters:
  disable:
    - gochecknoinits
    - gofumpt
    - depguard
    - exhaustivestruct
    - gochecknoglobals
    - goerr113
    - wrapcheck
    - exhaustruct
    # TODO
    - forbidigo
    - deadcode
    - unused
